# fly.toml app configuration file generated for discord-reminder-bot on 2023-08-30T12:04:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-reminder-bot"
primary_region = "dfw"